app/forms/contact_form.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import SelectField, SubmitField, StringField, TextAreaField
import wtforms.validators as validators


class ContactForm(FlaskForm):

    email = StringField(
        "Your email",
        validators=[validators.DataRequired()],
        render_kw={"placeholder": "email@example.com", "class": "u-full-width"},
    )

    subject = SelectField(
        "Select a subject",
        choices=[
            ("hello", "Hello"),
        ],
        render_kw={"class": "u-full-width"},
    )

    message = TextAreaField(
        "Message",
        [validators.DataRequired(), validators.length(max=200)],
        render_kw={"placeholder": "Hello …", "class": "u-full-width"},
    )

    # recaptcha = RecaptchaField()

    submit = SubmitField(
        "Send",
        render_kw={
            "class": "button-primary-hollow",
            "style": "color: white; text-transform: none; font-size: initial;",
        },
    )

app/forms/pay_form.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import DecimalField, SelectField, SubmitField, TextAreaField
import wtforms.validators as validators


class PayForm(FlaskForm):

    amount = DecimalField(places=2, validators=[validators.DataRequired()])

    unit = SelectField(
        "Select a unit",
        choices=[("sat", "sat"), ("USD", "$"), ("GBP", "£"), ("EUR", "€")],
        render_kw={"class": "u-full-width"},
    )

    memo = TextAreaField(
        "Memo",
        [validators.length(max=200)],
        render_kw={"placeholder": "Invoice for …", "class": "u-full-width"},
    )

    # recaptcha = RecaptchaField()

    submit = SubmitField(
        "Create",
        render_kw={
            "class": "button-primary-hollow",
            "style": "color: white; text-transform: none; font-size: initial;",
        },
    )

app/__init__.py
import os
import sys
from dotenv import load_dotenv
from flask import Flask, redirect, url_for
from flask_mail import Mail
from flask_lnbits import LNbits
from flask_qrcode import QRcode
from flask_wtf.csrf import CSRFProtect
from app.config import Config

csrf = CSRFProtect()
lnbits = LNbits()
mail = Mail()
qr_code = QRcode()


def create_app() -> Flask:

    app = Flask(__name__, instance_relative_config=True)

    app.config.from_object(Config)

    csrf.init_app(app=app)
    lnbits.init_app(app=app)
    mail.state = mail.init_app(app=app)
    qr_code.init_app(app=app)

    with app.app_context():

        from app.blueprints.about_bp import about_bp
        from app.blueprints.contact_bp import contact_bp
        from app.blueprints.index_bp import index_bp
        from app.blueprints.legal_bp import legal_bp
        from app.blueprints.pay_bp import pay_bp
        from app.blueprints.webhooks_bp import webhooks_bp

        app.register_blueprint(about_bp, url_prefix="/about")
        app.register_blueprint(contact_bp, url_prefix="/contact")
        app.register_blueprint(index_bp, url_prefix="/")
        app.register_blueprint(legal_bp, url_prefix="/legal")
        app.register_blueprint(pay_bp, url_prefix="/pay")
        app.register_blueprint(webhooks_bp, url_prefix="/webhooks")

        return app

app/blueprints/about_bp.py
from flask import Blueprint, jsonify, render_template, request

about_bp = Blueprint("about_bp", __name__)


@about_bp.route("/", methods=["GET"])
def get():
    print(__name__, "get")
    return render_template("about.html"), 200

app/blueprints/contact_bp.py
from flask import Blueprint, flash, jsonify, redirect, render_template, request, url_for
from app import mail
from app.forms.contact_form import ContactForm
from app.utils.email import send

contact_bp = Blueprint("contact_bp", __name__)


@contact_bp.route("/", methods=["GET"])
def get():
    print(__name__, "get")
    form = ContactForm()
    return render_template("contact.html", form=form)


@contact_bp.route("/send-message", methods=["POST"])
def send_message():
    print(__name__, "send_message")
    form = ContactForm()
    if form.validate_on_submit():
        send(
            sender=form.email.data,
            recipient=mail.username,
            subject=form.subject.data,
            html=form.message.data,
        )
        flash(message="Email sent!", category="success")
        return redirect(url_for("contact_bp.get"))
    return render_template("contact.html", form=form)

app/blueprints/index_bp.py
from flask import Blueprint, jsonify, redirect, render_template, request, url_for

index_bp = Blueprint("index_bp", __name__)


@index_bp.route("/", methods=["GET"])
def get():
    print(__name__, "get")
    return render_template("index.html"), 200

app/blueprints/legal_bp.py
from flask import Blueprint, jsonify, render_template, request

legal_bp = Blueprint("legal_bp", __name__)


@legal_bp.route("/", methods=["GET"])
def get():
    print(__name__, "get")
    return render_template("legal.html"), 200

app/blueprints/pay_bp.py
from decimal import Decimal
import json
from flask import Blueprint, flash, jsonify, render_template, request
from app.forms.pay_form import PayForm


from app import lnbits

pay_bp = Blueprint("pay_bp", __name__)


@pay_bp.route("", methods=["GET"])
@pay_bp.route("/", methods=["GET"])
def get():
    print(__name__, "get")
    data = lnbits.get_lnurlp()
    form = PayForm()
    return render_template("pay.html", data=data, form=form), 200


@pay_bp.route("/invoice", methods=["POST"])
def invoice():
    print(__name__, "invoice")
    form = PayForm()
    if form.validate_on_submit():
        data = lnbits.create_invoice(
            unit=form.unit.data,
            amount=form.amount.data,
            memo=form.memo.data,
        )
        flash(message="Please pay the invoice!", category="success")
        return render_template("pay-invoice.html", data=data), 200
    flash(
        message="Error generating invoice. Please refresh and try again",
        category="error",
    )
    return redirect(url_for("pay_bp.get"))

app/blueprints/webhooks_bp.py
import hashlib
import hmac
import six
import subprocess
from flask import Blueprint, jsonify, request
from flask import current_app as app

webhooks_bp = Blueprint("webhooks_bp", __name__)


@webhooks_bp.route("/github", methods=["GET", "POST"])
def github():
    """Triggered when a push request is made to GitHub. To add a GitHub webhook go to the
    following URL:

        https://github.com/<USER>/<REPO>/settings/hooks/new

    and add these parameters:

        Payload URL: https://<SERVER_IP>:<SERVER_PORT>/api/webhooks/github
        content type: application/json
        secret: <GITHUB_SECRET>

    """
    print(__name__, "github")
    try:
        secret = app.config["GITHUB_SECRET"].encode("utf-8")
        digest = six.text_type(hmac.new(secret, request.data, hashlib.sha1).hexdigest())
        sig_parts = request.headers["X-Hub-Signature"].split("sha1=")
        if not hmac.compare_digest(sig_parts[1], digest):
            raise ValueError("GITHUB_SECRET does not match.")
        result = subprocess.run(
            ["git", "pull"], stdout=subprocess.STDOUT, stderr=subprocess.STDOUT
        )
        if result.returncode != 0:
            raise Exception((str(result.stdout)))
    except Exception as e:
        return jsonify({"Error": f"{e}"}), 400
    else:
        return jsonify({}), 200

app/templates/base.html
<!DOCTYPE html>

<html lang="en" id="html">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ config["WEBSITE_NAME"] }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/vendor/fontawesome-free-6.2.0-web/css/all.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/vendor/Skeleton-2.0.4/css/normalize.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/vendor/Skeleton-2.0.4/css/skeleton.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">
    <!-- <link href="data:image/x-icon;base64,{{ config['WEBSITE_LOGO'] }}" rel="icon" type="image/x-icon" /> -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
    {% block head %}{% endblock head %}
  </head>
  <body>
     
    <div id="hide-me" class="container">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
          <br>
          <div class="row flashes {{ category }}">
            {{ message }}
          </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      </div>
    </div>
    <div class="container">
      <br>
      <br>
      <div class="row">
        <div class="twelve columns">
          <h3><b>{{ config["WEBSITE_NAME"] }}</b></h3>
        </div>
      </div>
      <div class="row">
        <div class="twelve columns">
          <!-- <img class="logo" src="data:image/png;base64, {{ config['WEBSITE_LOGO'] }}"> -->
          <!-- <img class="logo" src="{{ url_for('static', filename='img/logo.png') }}"> -->
          <img class="logo" src="{{ url_for('static', filename='img/logo.png') }}">
        </div>
      </div>
      <div class="row">
        <div class="twelve columns">
          <br>
          <h5><b>{{ config["WEBSITE_SLOGAN"] }}</b></h5>
        </div>
      </div>
    </div>
      <br>
    <div class="container">
      <div class="row">
        <!-- <div class="three columns"> -->
        <div class="four columns">
          <button
            class='{{"button-primary-filled" if active_page == "about" else "button-primary-hollow"}}'
            onclick="window.location.href='{{ url_for('about_bp.get')}}';">
              <i class="fa-solid fa-info"></i>
              &nbsp;
              About
          </button>
        </div>
        <!-- <div class="three columns"> -->
        <div class="four columns">
          <button
            class='{{"button-primary-filled" if active_page == "contact" else "button-primary-hollow"}}'
            onclick="window.location.href='{{ url_for('contact_bp.get')}}';">
              <i class="fa-regular fa-comment"></i>
              &nbsp;
              Contact
          </button>
        </div>
        <!-- <div class="three columns"> -->
        <div class="four columns">
          <button
            class='{{"button-primary-filled" if active_page == "pay" else "button-primary-hollow"}}'
            onclick="window.location.href='{{ url_for('pay_bp.get')}}';">
              <i class="fa-brands fa-btc"></i>
              &nbsp;
              Pay
          </button>
        </div>
        <!-- <div class="three columns"> -->
          <!-- <button -->
            <!-- class='{{"button-primary-filled" if active_page == "legal" else "button-primary-hollow"}}' -->
            <!-- onclick="window.location.href='{{ url_for('legal_bp.get')}}';"> -->
              <!-- <i class="fa-solid fa-gavel"></i> -->
              <!-- &nbsp; -->
              <!-- Legal -->
          <!-- </button> -->
        <!-- </div> -->
      </div>
    </div>
    <br>
    <br>
    <div class="container">
      {% block content %}{% endblock content %}
    </div>
    <br>
    <br>

    <div class="container">
      <div class="row">
        <div class="twelve columns">
          {% if config["MAIL_USERNAME"] != "" %}
            <a href="mailto:{{ config['MAIL_USERNAME'] }}?subject=Hello!"><i class="fa fa-envelope fa-2xl"></i></a>
            &nbsp;
            &nbsp;
            &nbsp;
          {% endif %}
          {% if config["WEBSITE_TIKTOK"] != "" %}
            <a href="https://www.tiktok.com/@{{ config['WEBSITE_TIKTOK'] }}" target=”_blank”><i class="fa-brands fa-tiktok fa-2xl"></i></a>
            &nbsp;
            &nbsp;
            &nbsp;
          {% endif %}
          {% if config["WEBSITE_INSTAGRAM"] != "" %}
            <a href="https://instagram.com/{{ config['WEBSITE_INSTAGRAM'] }}" target=”_blank”><i class="fa-brands fa-instagram fa-2xl"></i></a>
            &nbsp;
            &nbsp;
            &nbsp;
          {% endif %}
          {% if config["WEBSITE_TWITTER"] != "" %}
            <a href="https://twitter.com/{{ config['WEBSITE_TWITTER'] }}" target=”_blank”><i class="fa-brands fa-twitter fa-2xl"></i></a>
            &nbsp;
            &nbsp;
            &nbsp;
          {% endif %}
          {% if config["WEBSITE_GITHUB"] != "" %}
            <a href="https://github.com/{{ config['WEBSITE_GITHUB'] }}" target=”_blank”><i class="fa-brands fa-github fa-2xl"></i></a>
            &nbsp;
            &nbsp;
            &nbsp;
          {% endif %}

        </div>
      </div>
      <br>
      <br>
      <br>
    </div>
    <script src="{{ url_for('static', filename='js/custom.js') }}"></script>
    {% block scripts %}{% endblock scripts %}
  </body>
</html>

app/templates/contact.html
{% set active_page = "contact" %}
{% extends "base.html" %}

{% block content %}
<div>
  <h2>Contact</h2>  
</div>
<form action="{{ url_for('contact_bp.send_message') }}" method="POST">
  {{ form.csrf_token }}
  <div class="row">
    <div class="six columns">
      {{ form.subject.label }}
      {{ form.subject }}
    </div>
    <div class="six columns">
      {{ form.email.label }}
      {{ form.email }}
    </div>
  </div>
  {{ form.message.label }}
  {{ form.message }}
  <!-- { form.recapture }} -->
  {{ form.submit }}
</form>
{% if form.errors %}
  {{ form.errors }}
{% endif %}
{% endblock content %}

app/templates/index.html
{% set active_page = "index" %}
{% extends "base.html" %}

{% block content %}
<!-- <div class="row centered"> -->
    <!-- <div class="twelve columns"> -->
        <!-- Please select a tab above … -->
    <!-- </div> -->
<!-- </div> -->
{% endblock content %}

app/templates/legal.html
{% set active_page = "legal" %}
{% extends "base.html" %}

{% block content %}

<!-- <div class="row"> -->
  <!-- <div class="twelve columns"> -->
    <!-- <b>Last updated on YYYY-MM-DD</b> -->
  <!-- </div> -->
<!-- </div> -->
<!-- <br> -->

<div class="row">
  <div class="six columns">
    <button class="button-primary-filled" id="privacy-policy-button" onclick="toggle(['privacy-policy', 'terms-of-service']);">
      Privacy Policy
    </button>
  </div>
  <div class="six columns">
    <button class="button-primary-hollow" id="terms-of-service-button" onclick="toggle(['privacy-policy', 'terms-of-service']);">
      Terms of Service
    </button>
  </div>
</div>
<br>
<br>

<div id="privacy-policy" style="display: block;">
  <div class="row">
    <div class="twelve columns">
      <h2>Privacy Policy</h2>
    </div>
  </div>
  <div class="row">
    <div class="twelve columns">
      Your privacy is important to us. It is {{ config["WEBSITE_NAME"] }}'s policy to respect your privacy regarding any information we may collect from you across our website, <a href="{{ config['WEBSITE_URL'] }}">{{ config["WEBSITE_URL"] }}</a>, and other sites we own and operate.
    </div>
  </div>
  <br>
  <div class="row">
    <div class="twelve columns">
      We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and lawful means, with your knowledge and consent.
    </div>
  </div>
  <br>
  <div class="row">
    <div class="twelve columns">
      We also let you know why we're collecting it and how it will be used. We only retain collected information for as long as necessary to provide you with your requested service.
      What data we store, we'll protect within commercially acceptable means to prevent loss and theft, as well as unauthorised access, disclosure, copying, use or modification.
    </div>
  </div>
  <br>
  <div class="row">
    <div class="twelve columns">
      We don't share any personally identifying information publicly or with third parties, except when required to by law. Our website may link to external sites that are not operated by us. Please be aware that we have no control over the content and practices of these sites, and cannot accept responsibility or liability for their respective privacy policies
    </div>
  </div>
  <br>
  <div class="row">
    <div class="twelve columns">
      You are free to refuse our request for your personal information, with the understanding that we may be unable to provide you with some of your desired services. Your continued use of our website will be regarded as acceptance of our practices around privacy and personal information. If you have any questions about how we handle user data and personal information, feel free to contact us.
    </div>
  </div>
</div>

<div id="terms-of-service" style="display: none;">
  <h4>1. The Terms</h4>
  <p>By accessing the website at <a href="{{ config['WEBSITE_URL'] }}">{{ config["WEBSITE_URL"] }}</a>, you are agreeing to be bound by these terms of service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this website are protected by applicable copyright and trademark law.</p>
  <h4>2. Use Licence</h4>
  <ol type="a">
     <li>Permission is granted to temporarily download one copy of the materials (information or software) on <b>{{ config["WEBSITE_NAME"] }}</b>'s website for personal, non-commercial transitory viewing only. This is the grant of a licence, not a transfer of title, and under this licence you may not:
     <ol type="i">
         <li>modify or copy the materials;</li>
         <li>use the materials for any commercial purpose, or for any public display (commercial or non-commercial);</li>
         <li>attempt to decompile or reverse engineer any software contained on <b>{{ config["WEBSITE_NAME"] }}</b>'s website;</li>
         <li>remove any copyright or other proprietary notations from the materials; or</li>
         <li>transfer the materials to another person or "mirror" the materials on any other server.</li>
     </ol>
      </li>
     <li>This licence shall automatically terminate if you violate any of these restrictions and may be terminated by <b>{{ config["WEBSITE_NAME"] }}</b> at any time. Upon terminating your viewing of these materials or upon the termination of this licence, you must destroy any downloaded materials in your possession whether in electronic or printed format.</li>
  </ol>
  <h4>3. Disclaimer</h4>
  <ol type="a">
     <li>The materials on <b>{{ config["WEBSITE_NAME"] }}</b>'s website are provided on an 'as is' basis. <b>{{ config["WEBSITE_NAME"] }}</b> makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.</li>
     <li>Further, <b>{{ config["WEBSITE_NAME"] }}</b> does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its website or otherwise relating to such materials or on any sites linked to this site.</li>
  </ol>
  <h4>4. Limitations</h4>
  <p>In no event shall <b>{{ config["WEBSITE_NAME"] }}</b> or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on <b>{{ config["WEBSITE_NAME"] }}</b>'s website, even if <b>{{ config["WEBSITE_NAME"] }}</b> or a <b>{{ config["WEBSITE_NAME"] }}</b> authorised representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.</p>
  <h4>5. Accuracy of materials</h4>
  <p>The materials appearing on <b>{{ config["WEBSITE_NAME"] }}</b>'s website could include technical, typographical, or photographic errors. <b>{{ config["WEBSITE_NAME"] }}</b> does not warrant that any of the materials on its website are accurate, complete or current. <b>{{ config["WEBSITE_NAME"] }}</b> may make changes to the materials contained on its website at any time without notice. However <b>{{ config["WEBSITE_NAME"] }}</b> does not make any commitment to update the materials.</p>
  <h4>6. Links</h4>
  <p><b>{{ config["WEBSITE_NAME"] }}</b> has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by <b>{{ config["WEBSITE_NAME"] }}</b> of the site. Use of any such linked website is at the user's own risk.</p>
  <h4>7. Modifications</h4>
  <p><b>{{ config["WEBSITE_NAME"] }}</b> may revise these terms of service for its website at any time without notice. By using this website you are agreeing to be bound by the then current version of these terms of service.</p>
  <h4>8. Governing Law</h4>
  <p>These terms and conditions are governed by and construed in accordance with the laws of The United Kingdom and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.</p>
</div>
{% endblock content %}

app/templates/pay-invoice.html
{% set active_page = "pay-invoice" %}
{% extends "base.html" %}

{% block content %}

<h2>Invoice</h2>
<br>

<div class="row">
  <div class="twelve columns">
    <b>Created on</b>: &nbsp; {{ data["date"] }}
    <br>
    <b>Amount due</b>: &nbsp; {{ data["unit"] }} &nbsp; {{ data["amount"] }}
  </div>
</div>
<br>

<div class="row">
  <div class="twelve columns">
    <img src="{{ qrcode(data['payment_request']) }}" style="width: 300px; height: 300px;">
  </div>
</div>

{% endblock content %}

app/templates/pay.html
{% set active_page = "pay" %}
{% extends "base.html" %}

{% block content %}

      <h2>Pay</h2>
<br>

<div class="row">
  <div class="six columns">
    <button class="button-primary-filled" id="pay-invoice-button" onclick="toggle(['pay-lnurl', 'pay-invoice']);">
<i class="fas fa-file-invoice"></i>&nbsp;
      Invoice
    </button>
  </div>
  <div class="six columns">
    <button class="button-primary-hollow" id="pay-lnurl-button" onclick="toggle(['pay-lnurl', 'pay-invoice']);">
<i class="fa-solid fa-globe"></i>&nbsp;
      LNURL
    </button>
  </div>  
</div>
<br>
<br>

<div id="pay-lnurl" style="display: none;">
  <div class="row">
    <div class="twelve columns">
      <h2>LNURL</h2>
    </div>
  </div>
  <div class="row">
    <div class="twelve columns">
      <img src="{{ qrcode(data['lnurl']) }}" style="width: 300px; height: 300px;">
    </div>
  </div>
</div>

<div id="pay-invoice" style="display: block;">
  <div class="row">
    <div class="twelve columns">
      <h2>Invoice</h2>
      <form action="{{ url_for('pay_bp.invoice') }}" method="POST">
        {{ form.csrf_token }}
        <div class="row">
          <div class="two columns">
            {{ form.unit.label }}
            {{ form.unit }}
          </div>
          <div class="ten columns">
            {{ form.amount.label }}
            {{ form.amount }}
          </div>
        </div>
        {{ form.memo.label }}
        {{ form.memo }}
        <!-- { form.recapture }} -->
        {{ form.submit }}
      </form>
      {% if form.errors %}
        {{ form.errors }}
      {% endif %}
    </div>
  </div>
</div>

{% endblock content %}